export default {
  SUBMIT_QUESTION: '@@SUBMIT_QUESTION',
  UPDATE_ANSWER: '@@UPDATE_ANSWER',
  NEXT_QUESTION: '@@NEXT_QUESTION',
  PREVIOUS_QUESTION: '@@PREVIOUS_QUESTION',
  INITIATE_QUIZ: '@@INITIATE_QUIZ',
  CHANGE_CATEGORY: '@@CHANGE_CATEGORY',
  GET_CATEGORY: '@@GET_CATEGORY',
  LOAD_QUESTIONS_FOR_CHOSEN_CATEGORY: '@@LOAD_QUESTIONS_FOR_CHOSEN_CATEGORY',
};
