export default {
  SUBMIT_QUESTION: '@@SUBMIT_QUESTION',
  UPDATE_ANSWER: '@@UPDATE_ANSWER',
  NEXT_QUESTION: '@@NEXT_QUESTION',
  PREVIOUS_QUESTION: '@@PREVIOUS_QUESTION',
  INITIATE_QUIZ: '@@INITIATE_QUIZ',
  LOCATION_CHANGE: '@@LOCATION_CHANGE',
};
